Output demo.gif

Set Shell "bash"
Set FontSize 32
Set Width 1200
Set Height 600
Set TypingSpeed 100ms

Require "./build/calc"

Hide
Type "./build/calc" Enter
Ctrl+L
Sleep 1ms
Show

Type "5!" Sleep 300ms Enter Sleep 500ms
Type "sin(pi / 2)" Sleep 300ms Enter Sleep 500ms
Type "2^3 + sqrt 9" Sleep 300ms Enter Sleep 500ms
Type "factorial(5)" Sleep 300ms Enter Sleep 500ms
Type "min(3, 5, -1)" Sleep 300ms Enter Sleep 500ms
Type "3!!" Sleep 300ms Enter Sleep 500ms

Sleep 5s

Hide Ctrl+D
