### ! GENERATED BY CHATGPT ###
### ! EDIT IT LATER AFTER U LEARN MAKE ###


# Compiler and linker
CC := gcc
LDFLAGS := -lm

# Base flags
CFLAGS := -Wall -Wextra -std=c99

# Directories
BUILD_DIR := build
EVAL_DIR := eval
INCLUDE := include
TEST_DIR := test

# Sources
SRC := main.c $(EVAL_DIR)/eval_expr.c $(EVAL_DIR)/function.c
HEADERS := $(EVAL_DIR)/eval_expr.h $(INCLUDE)/error.h
TEST_SRC := $(TEST_DIR)/test_eval.c

# Outputs
DEBUG_BIN := $(BUILD_DIR)/calc_debug
RELEASE_BIN := $(BUILD_DIR)/calc
TEST_BIN := $(BUILD_DIR)/test

# Ensure build dir exists
$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

.PHONY: debug release test clean

debug: CFLAGS += -g -O0 -DDEBUG
debug: $(DEBUG_BIN)

release: CFLAGS += -O2
release: $(RELEASE_BIN)

test: CFLAGS += -g -O0 -DDEBUG
test: $(TEST_BIN)
	./$(TEST_BIN)

$(DEBUG_BIN): $(SRC) $(HEADERS) | $(BUILD_DIR)
	$(CC) $(CFLAGS) -I$(INCLUDE) -I$(EVAL_DIR) -o $@ $(SRC) $(LDFLAGS)

$(RELEASE_BIN): $(SRC) $(HEADERS) | $(BUILD_DIR)
	$(CC) $(CFLAGS) -I$(INCLUDE) -I$(EVAL_DIR) -o $@ $(SRC) $(LDFLAGS)

$(TEST_BIN): $(TEST_SRC) $(HEADERS) $(EVAL_DIR)/eval_expr.c $(EVAL_DIR)/function.c | $(BUILD_DIR)
	$(CC) $(CFLAGS) -I$(INCLUDE) -I$(EVAL_DIR) -o $@ $(TEST_SRC) $(EVAL_DIR)/eval_expr.c $(EVAL_DIR)/function.c $(LDFLAGS)

clean:
	rm -rf $(BUILD_DIR)